Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\adaptive_wear_generator_pro\__init__.py", line 14, in <module>
    from . import core
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\adaptive_wear_generator_pro\core\__init__.py", line 2, in <module>
    from .mesh_generator import AWGP_OT_GenerateGarment # AWGP_OT_GeneratePants を削除
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'AWGP_OT_GenerateGarment' from 'adaptive_wear_generator_pro.core.mesh_generator' (C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\adaptive_wear_generator_pro\core\mesh_generator.py)
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\adaptive_wear_generator_pro\__init__.py", line 14, in <module>
    from . import core
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\adaptive_wear_generator_pro\core\__init__.py", line 2, in <module>
    from .mesh_generator import AWGP_OT_GenerateGarment # AWGP_OT_GeneratePants を削除
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'AWGP_OT_GenerateGarment' from 'adaptive_wear_generator_pro.core.mesh_generator' (C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\adaptive_wear_generator_pro\core\mesh_generator.py)
